# Generated by Django 5.1.6 on 2025-03-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AeroMaster_admin', '0002_archivefaculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
