# Generated by Django 5.1.6 on 2025-03-20 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AeroMaster_admin', '0002_aero_master_admin_delete_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aero_Master_admin',
            new_name='AeroMaster_admin',
        ),
    ]
