# Generated by Django 5.1.6 on 2025-03-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AeroMaster_admin', '0003_archivestudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeromaster_admin',
            name='role',
            field=models.CharField(default='aeromaster_admin', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='archivefaculty',
            name='role',
            field=models.CharField(default='faculty', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='archivestudent',
            name='role',
            field=models.CharField(default='user', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='faculty',
            name='role',
            field=models.CharField(default='faculty', editable=False, max_length=20),
        ),
    ]
