# Generated by Django 5.1.6 on 2025-03-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AeroMaster_admin', '0003_rename_aero_master_admin_aeromaster_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='username',
            new_name='emp_id',
        ),
    ]
