# Generated by Django 5.1.6 on 2025-04-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AeroMaster_admin', '0005_rename_generatedquestion_generatedquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('shuffle', models.BooleanField(default=True)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
