# Generated by Django 5.1.6 on 2025-04-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AeroMaster_admin', '0006_examsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('aero_result', models.IntegerField()),
                ('math_result', models.IntegerField()),
                ('struc_result', models.IntegerField()),
                ('acrm_result', models.IntegerField()),
                ('pwrp_result', models.IntegerField()),
                ('eemle_result', models.IntegerField()),
            ],
        ),
    ]
