# Generated by Django 5.1.6 on 2025-04-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AeroMaster_admin', '0008_alter_examresult_acrm_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsetting',
            name='passing_score',
            field=models.IntegerField(default=38),
        ),
    ]
