# Generated by Django 5.1.6 on 2025-04-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AeroMaster_admin', '0009_examsetting_passing_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('satisfaction', models.IntegerField(choices=[(1, 'Dissatisfied'), (2, 'Satisfied'), (3, 'Very Satisfied')])),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
