# Generated by Django 5.1.6 on 2025-04-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AeroMaster_admin', '0011_examresult_percent_result_examresult_total_result_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfeedback',
            old_name='comments',
            new_name='acrm_comments',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='satisfaction',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='subject',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='acrm_satisfaction',
            field=models.IntegerField(blank=True, choices=[(1, 'Dissatisfied'), (2, 'Satisfied'), (3, 'Very Satisfied')], null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='aero_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='aero_satisfaction',
            field=models.IntegerField(blank=True, choices=[(1, 'Dissatisfied'), (2, 'Satisfied'), (3, 'Very Satisfied')], null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='eemle_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='eemle_satisfaction',
            field=models.IntegerField(blank=True, choices=[(1, 'Dissatisfied'), (2, 'Satisfied'), (3, 'Very Satisfied')], null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='math_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='math_satisfaction',
            field=models.IntegerField(blank=True, choices=[(1, 'Dissatisfied'), (2, 'Satisfied'), (3, 'Very Satisfied')], null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='pwrp_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='pwrp_satisfaction',
            field=models.IntegerField(blank=True, choices=[(1, 'Dissatisfied'), (2, 'Satisfied'), (3, 'Very Satisfied')], null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='struc_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='struc_satisfaction',
            field=models.IntegerField(blank=True, choices=[(1, 'Dissatisfied'), (2, 'Satisfied'), (3, 'Very Satisfied')], null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='acrm_result',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='aero_result',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='eemle_result',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='math_result',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='percent_result',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='pwrp_result',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='struc_result',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='total_result',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
