# Generated by Django 5.1.6 on 2025-04-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AeroMaster_admin', '0012_rename_comments_userfeedback_acrm_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='acrm_time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='aero_time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='eemle_time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='math_time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='pwrp_time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='struc_time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
