from django.urls import path
from .views import (admin_view, faculty_list, edit_faculty, archive_faculty, add_faculty,
                    student_list, edit_student, archive_student, add_student,
                    login_admin_view, login_acc, logout_view,
                    question_list, edit_question, add_question, archive_question,
                    panel_view, generate_questions, dashboard_view,
                    export_user, import_user, export_question, import_question, export_faculty, import_faculty,
                    export_feedback, reset_exam)

urlpatterns = [
    path('', admin_view, name='AeroMaster_admin'),
    path('faculty/view', faculty_list, name='faculty_list'),
    path('faculty/add/', add_faculty, name='add_faculty'),
    path('faculty/edit/<str:faculty_id>/', edit_faculty, name='edit_faculty'),
    path('faculty/delete/<str:faculty_id>/', archive_faculty, name='archive_faculty'),
    path('student/view', student_list, name='student_list'),
    path('student/add/', add_student, name='add_student'),
    path('student/edit/<str:student_id>/', edit_student, name='edit_student'),
    path('student/delete/<str:student_id>/', archive_student, name='archive_student'),
    path('login/', login_admin_view, name='login_admin'),
    path('login_acc/', login_acc, name='AeroMasterAdmin_login_acc'),
    path('logout/', logout_view, name='logout_admin'),
    path('question/view', question_list, name='question_list'),
    path('question/add/', add_question, name='add_question'),
    path('question/edit/<str:id>/', edit_question, name='edit_question'),
    path('question/delete/<str:id>/', archive_question, name='archive_question'),
    path('panel', panel_view, name='panel'),
    path('panel/generate/', generate_questions, name='generate'),
    path('panel/reset/', reset_exam, name='reset_exam'),
    path('dashboard/', dashboard_view, name='dashboard'),
    path('export_user/', export_user, name='export_user'),
    path('student/import/', import_user, name='import_user'),
    path('export_question/', export_question, name='export_question'),
    path('question/import/', import_question, name='import_question'),
    path('export_faculty/', export_faculty, name='export_faculty'),
    path('export_feedback/', export_feedback, name='export_feedback'),
    path('faculty/import/', import_faculty, name='import_faculty'),
    #path('panel/setting/', edit_exam_settings, name='exam_settings'),
]
