# Generated by Django 5.1.6 on 2025-03-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AeroMaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
