# Generated by Django 5.1.6 on 2025-04-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AeroMaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
