# Generated by Django 5.1.6 on 2025-04-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AeroMaster', '0002_user_middle_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Student',
        ),
    ]
