# Generated by Django 5.1.6 on 2025-03-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AeroMaster', '0002_alter_user_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', editable=False, max_length=20),
        ),
    ]
